### ISSUE TITLE
Unable to use inside fragment

### ISSUE THREAD

**Issue by RahilRK** [Ajinkrishnak/CountryCodePicker#1]
java.lang.ClassCastException: dagger.hilt.android.internal.managers.ViewComponentManager$FragmentContextWrapper cannot be cast to androidx.fragment.app.FragmentActivity
        at com.ak.ui.CountryCodePicker._init_$lambda-1(CountryCodePicker.kt:103)
        at com.ak.ui.CountryCodePicker.$r8$lambda$wRnhXw3yJa1VGy1WI3ZuYEDCZdU(CountryCodePicker.kt)
        at com.ak.ui.CountryCodePicker$$ExternalSyntheticLambda0.onClick(Unknown Source)
        at android.view.View.performClick(View.java:5637)
        at android.view.View$PerformClick.run(View.java:22429)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
    
    
    --------- beginning of system

**Comment by TwinsOd** [comment]
I got same error(
